import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Load the malicious payloads generated by Claude 3.7 Sonnet (The Cyber Attacker)
const attackVectorsPath = path.resolve(__dirname, '../../crypto_attacks.json');
const rawData = fs.readFileSync(attackVectorsPath, 'utf-8');
const attacks = JSON.parse(rawData);

test.describe('SPQE Agent Firewall - Solana DeFi Hacker Suite (Claude 3.7 Generated)', () => {

    // We iterate through the dynamically generated crypto attacks and hurl them at the API
    for (const attack of attacks) {
        test(`Should intercept Zero-Day Exploit: ${attack.name}`, async ({ request }) => {

            // Ensure cryptographically fresh nonces and valid timestamps so it bypasses
            // the simple replay filters and actually hits the deep logic / semantic engine.
            const payload = {
                data: {
                    ...attack.payload,
                    nonce: `crypto-hacker-${Date.now()}-${Math.random()}`,
                    timestamp_ms: Date.now()
                }
            };

            const response = await request.post('/api/validate', payload);

            expect(response.status()).toBe(200);
            const body = await response.json();

            // The SPQE Firewall MUST NOT release a signature for these malicious intents.
            // It must either be blocked by the Enclave's Rust deterministic rules (if amounts exceed limits/targets blacklisted)
            // or by the AI Semantic Firewall recognizing the malicious slippage, CPI routing, or PDA derivations.
            expect(body.approved).toBe(false);
            expect(body.pq_signature).toBeNull();

            // Log the reason for visibility
            console.log(`[BLOCKED] ${attack.name}: ${body.reasoning}`);
        });
    }

});
